import React, { useState } from 'react';
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  Badge,
  Button,
  DatePicker,
  Table,
  useToast
} from '../component';
import { FileText, Download, FileSpreadsheet } from 'lucide-react';

export const Reports = () => {
  const toast = useToast();
  const [timeRange, setTimeRange] = useState('today');

  const reportsList = [
    {
      id: 'REP-2026-0901',
      title: 'Daily Consolidated Traffic & Flow Audit',
      period: 'Today (Past 24 Hours)',
      generatedBy: 'System AI Engine',
      size: '2.4 MB',
      format: 'PDF / CSV',
      status: 'Ready'
    },
    {
      id: 'REP-2026-0902',
      title: 'E-Challan Violation & Penalty Recovery Summary',
      period: 'Sept 1 - Sept 20, 2026',
      generatedBy: 'Enforcement Division',
      size: '4.8 MB',
      format: 'PDF / XLSX',
      status: 'Ready'
    },
    {
      id: 'REP-2026-0903',
      title: 'High-Density Corridor Bottleneck Analysis',
      period: 'Last 7 Days',
      generatedBy: 'Smart City Analytics',
      size: '1.8 MB',
      format: 'PDF',
      status: 'Ready'
    },
    {
      id: 'REP-2026-0904',
      title: 'CCTV Optical Sensor Uptime & MTBF Log',
      period: 'Monthly (August 2026)',
      generatedBy: 'Hardware Operations',
      size: '850 KB',
      format: 'PDF / CSV',
      status: 'Archived'
    }
  ];

  const columns = [
    {
      key: 'id',
      label: 'Report ID',
      render: (val) => <span className="font-mono text-cyan-300 font-semibold">{val}</span>
    },
    {
      key: 'title',
      label: 'Report Title',
      render: (val, row) => (
        <div>
          <p className="font-semibold text-slate-100">{val}</p>
          <span className="text-[11px] text-slate-400">Coverage: {row.period}</span>
        </div>
      )
    },
    { key: 'generatedBy', label: 'Generated By' },
    { key: 'format', label: 'Format' },
    {
      key: 'status',
      label: 'Status',
      render: (val) => (
        <Badge variant={val === 'Ready' ? 'success' : 'neutral'} dot={val === 'Ready'}>
          {val}
        </Badge>
      )
    },
    {
      key: 'action',
      label: 'Download',
      align: 'right',
      render: (_, row) => (
        <div className="flex items-center justify-end gap-2">
          <Button
            variant="outline"
            size="xs"
            leftIcon={<Download className="w-3.5 h-3.5" />}
            onClick={() => {
              toast.addToast({
                type: 'success',
                title: 'Download Initiated',
                message: `Downloading ${row.title} (${row.format})`
              });
            }}
          >
            Download
          </Button>
        </div>
      )
    }
  ];

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyan-400" />
            Enforcement & Traffic Intelligence Reports
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Automated statutory compliance, violation audits, and smart city data exports
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <DatePicker value={timeRange} onChange={(val) => setTimeRange(val)} />
          <Button
            variant="primary"
            size="sm"
            leftIcon={<FileSpreadsheet className="w-4 h-4" />}
            onClick={() => {
              toast.addToast({
                type: 'info',
                title: 'Generating New Report',
                message: 'Compiling latest 24h telemetry dataset into PDF...'
              });
            }}
          >
            Generate Custom Audit
          </Button>
        </div>
      </div>

      <Card variant="default">
        <CardHeader>
          <CardTitle>Available Operational Reports</CardTitle>
          <CardDescription>Validated by the Municipal Transport & Enforcement Authority</CardDescription>
        </CardHeader>
        <CardContent>
          <Table columns={columns} data={reportsList} />
        </CardContent>
      </Card>
    </div>
  );
};

export default Reports;
